COPIER_HEADER_SIZE = 512

LABEL_MAP_MODE = "Map Mode"
LABEL_COMPLEMENT = "Complement"
LABEL_CHECKSUM = "Checksum"

LABEL_MAPSPEED = "Map/Speed"
MAPSPEED_BITS_FIXED_0 = [7,6,3]
MAPSPEED_BITS_FIXED_1 = [5]
MAPSPEED_BIT_SPEED = 4
MAPSPEED_BIT_EX = 2
MAPSPEED_BIT_SPECIAL = 1
MAPSPEED_BIT_HI_LO = 0

SPEED_MODE_SLOW, SPEED_MODE_FAST = 0, 1
SPEED_MODE_LABELS = [
    [SPEED_MODE_SLOW, "Slow"],
    [SPEED_MODE_FAST, "Fast"]
]
SPEED_MODE_LABELS = dict(SPEED_MODE_LABELS)


LABEL_ROM_LO = "LoROM"
LABEL_ROM_HI = "HiROM"
LABEL_ROM_EXHI = "ExHiROM"
LABEL_ROM_SA_1 = "SA-1 ROM"
LABEL_ROM_SDD_1 = "SDD-1 ROM"
LABEL_ROM_UNKN = "Unknown ROM"
HI_LO_MODE_LOROM, HI_LO_MODE_HIROM = 0, 1
HI_LO_MODE_LABELS = [
    [HI_LO_MODE_LOROM, LABEL_ROM_LO],
    [HI_LO_MODE_HIROM, LABEL_ROM_HI]
]
HI_LO_MODE_LABELS = dict(HI_LO_MODE_LABELS)

HEADER_OFFSETS = [
    [LABEL_ROM_LO, 0x_7F_B0],
    [LABEL_ROM_HI, 0x_FF_B0],
    [LABEL_ROM_EXHI, 0x_40_FF_B0]
]
HEADER_OFFSETS = dict(HEADER_OFFSETS)

LABEL_MAKER_CODE = "Maker Code"
LABEL_GAME_CODE = "Game Code"
EX_HEADER_FIELDS = [
    (LABEL_MAKER_CODE, 2), 
    (LABEL_GAME_CODE, 4)
]

LABEL_DEV_ID = "Developer ID"
LABEL_EX_HEADER_FLAG = LABEL_DEV_ID
LABEL_PREFIX_EX_HEADER_RESERVED = "Fixed Byte"

LABELS_EX_HEADER_RESERVED =[f"{LABEL_PREFIX_EX_HEADER_RESERVED}[{i}]" for i in range(6)]
VALUE_EX_HEADER_RESERVED = 0x00
VALUE_EX_HEADER_FLAG = 0x33


EX_HEADER_FIELDS.extend([(i, 1) for i in LABELS_EX_HEADER_RESERVED])

LABEL_GAME_TITLE = "Game title"
LABEL_CHIPSET = "Chipset"
VALUE_CHIPSET_ROM_ONLY = 0x0
VALUE_CHIPSET_ROM_RAM = 0x1
VALUE_CHIPSET_ROM_RAM_BATTERY = 0x2
VALUE_CHIPSET_ROM_COPROCESSOR = 0x3
VALUE_CHIPSET_ROM_COPROCESSOR_RAM = 0x4
VALUE_CHIPSET_ROM_COPROCESSOR_RAM_BATTERY = 0x5
VALUE_CHIPSET_ROM_COPROCESSOR_BATTERY = 0x6
VALUE_CHIPSETS_WITH_COPROCESSOR = [
    VALUE_CHIPSET_ROM_COPROCESSOR,
    VALUE_CHIPSET_ROM_COPROCESSOR_RAM,
    VALUE_CHIPSET_ROM_COPROCESSOR_RAM_BATTERY,
    VALUE_CHIPSET_ROM_COPROCESSOR_BATTERY,
]

VALUE_COPROCESSOR_DSP = 0x0
VALUE_COPROCESSOR_GSU = 0x1
VALUE_COPROCESSOR_OBC1 = 0x2
VALUE_COPROCESSOR_SA1 = 0x3
VALUE_COPROCESSOR_SDD1 = 0x4
VALUE_COPROCESSOR_SRTC = 0x5
VALUE_COPROCESSOR_OTHER = 0xE
VALUE_COPROCESSOR_CUSTOM = 0xF

#$00 - Japan; #$01 - USA; #$02 - Europe (enables 50fps PAL mode)
LABEL_COUNTRY_CODE = "Country Code"
COUNTRY_CODE_DICTIONARY = {
    0x00 : 'Japan',  #0x00
    0x01 : 'USA',    #0x01
    0x02 : 'Europe'  #0x02
}

EX_HEADER_FIELDS.extend([
    ("ExFlash Size", 1), 
    ("ExRAM Size", 1), 
    ("Special Version", 1), 
    ("Cart SubType", 1)
])

HEADER_FIELDS = EX_HEADER_FIELDS
HEADER_FIELDS.extend([
    (LABEL_GAME_TITLE, 21), 
    (LABEL_MAPSPEED, 1), 
    (LABEL_CHIPSET, 1), 
    ("ROM Size", 1), 
    ("RAM Size", 1), 
    (LABEL_COUNTRY_CODE, 1), 
    (LABEL_DEV_ID, 1), 
    ("ROM version", 1),
    (LABEL_COMPLEMENT, 2),
    (LABEL_CHECKSUM, 2)
])
# nl = '\n'
# for x in HEADER_FIELDS:
#     print(f"{x}")