# ./src/common/constants.py

MAX_TWO_BYTE_INT = 0xFFFF
BYTE_ORDER_BIG_ENDIAN = 'big'
BYTE_ORDER_LITTLE_ENDIAN = 'little'


LABEL_CHECKSUM = "Checksum"
LABEL_COMPLEMENT = "Complement"
LABEL_BIG_ENDIAN = BYTE_ORDER_BIG_ENDIAN.title()
LABEL_ORDER_LITTLE_ENDIAN = BYTE_ORDER_LITTLE_ENDIAN.title()